steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 
    'gcr.io/$PROJECT_ID/frontend-react-app:$COMMIT_SHA', 
    'frontend/'
  ]
  dir: .
  id: "Build Docker Image"
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/frontend-react-app:$COMMIT_SHA'
  ]
  id: "Push Image to GCR"
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'config'
    - 'set'
    - 'compute/region'
    - '${_REGION}'
  id: 'Set Region'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - '${_CLUSTER_NAME}'
    - '--region'
    - '${_REGION}'
    - '--project'
    - '$PROJECT_ID'
  id: 'Authenticate with GKE'
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'frontend/deployment.yml'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  id: "Apply Deployment"
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set', 
    'image', 
    'deployment/react-deployment', 
    'react-app-container=${_IMAGE_NAME}', 
    '--namespace=default'
  ]
  env:
    - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'frontend/service.yml'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  id: "Apply Service Configuration"
substitutions:
  _CLUSTER_NAME: "reactcluster"
  _REGION: "us-east1"
  _IMAGE_NAME: "gcr.io/$PROJECT_ID/frontend-react-app:$COMMIT_SHA"
timeout: "600s"

options:
  logging: CLOUD_LOGGING_ONLY  # Optional, if you want logs to be stored in Cloud Logging only
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
