steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
     '-f', 
    'backend/Dockerfile',
    '-t', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA', 
    '/backend/'
  ]
  dir: .
  id: "Build Docker Image"
options:
  logging: CLOUD_LOGGING_ONLY  # Optional, if you want logs to be stored in Cloud Logging only
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
