steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA', 
    '.'
  ]
  dir: .
  id: "Build Docker Image"

  - name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA'
  ]
  id: "Push Image to GCR"


  
