steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA', 
    '.'
  ]
  dir: ./backend
  id: "Build Docker Image"
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA'
  ]
  id: "Push Image to GCR"
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'config'
    - 'set'
    - 'project'
    - '${_PROJECT_ID}'
  id: 'Set Project'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'config'
    - 'set'
    - 'compute/region'
    - '${_REGION}'
  id: 'Set Region'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'config'
    - 'set'
    - 'compute/zone'
    - '${_ZONE}'
  id: 'Set Zone'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - '${_CLUSTER_NAME}'
    - '--region'
    - '${_REGION}'
    - '--zone'
    - '${_ZONE}'
  id: 'Authenticate with GKE'
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'deployment.yml'
  ]
  id: "Apply Deployment"
  env: [
    'IMAGE=gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA'
  ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'service.yml'
  ]
  id: "Apply Service Configuration"
substitutions:
  _CLUSTER_NAME: "flaskcluster"
  _PROJECT_ID: "keen-bongo-400523"
  _REGION: "us-east1"
  _ZONE: "us-east1-c"
timeout: "600s"

options:
  logging: CLOUD_LOGGING_ONLY  # Optional, if you want logs to be stored in Cloud Logging only
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
