steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA', 
    '.'
  ]
  dir: ./backend
  id: "Build Docker Image"
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA'
  ]
  id: "Push Image to GCR"
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'config'
    - 'set'
    - 'compute/region'
    - '${_REGION}'
  id: 'Set Region'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - '${_CLUSTER_NAME}'
    - '--region'
    - '${_REGION}'
    - '--project'
    - '$PROJECT_ID'
  id: 'Authenticate with GKE'
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'deployment.yml'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'IMAGE=gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA'
  id: "Apply Deployment"
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'service.yml'
  ]
  id: "Apply Service Configuration"
substitutions:
  _CLUSTER_NAME: "flaskcluster"
  _REGION: "us-east1"
timeout: "600s"

options:
  logging: CLOUD_LOGGING_ONLY  # Optional, if you want logs to be stored in Cloud Logging only
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
