steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA', 
    '.'
  ]
  dir: ./backend
  id: "Build Docker Image"
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA'
  ]
  id: "Push Image to GCR"
- name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'flaskcluster', '--zone', 'us-east1-c', '--project', 'keen-bongo-400523']
  id: "Get GKE Credentials"
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'config', 
    'set-cluster', 
    '${_CLUSTER_NAME}'
  ]
  id: "Configure kubectl Context"
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'deployment.yml'
  ]
  id: "Apply Deployment"
  env: [
    'IMAGE=gcr.io/$PROJECT_ID/backend-flask-app:$COMMIT_SHA'
  ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 
    'service.yml'
  ]
  id: "Apply Service Configuration"

substitutions:
  _CLUSTER_NAME: "flaskcluster"
  _REGION: "us-east1"
timeout: "600s"

options:
  logging: CLOUD_LOGGING_ONLY  # Optional, if you want logs to be stored in Cloud Logging only
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
